
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE5A_NET(

	//////////// CLOCK //////////
	input 		          		CLKUSR_100,
	input 		          		CLK_100_B3D,
	input 		          		CLK_50_B2J,
	input 		          		CLK_50_B2L,
	input 		          		CLK_50_B3D,
	input 		          		CLK_50_B3F,
	input 		          		CLK_50_B3H,

	//////////// KEY //////////
	input 		     [3:0]		BUTTON,
	input 		          		CPU_RESET_n,

	//////////// SW //////////
	input 		     [1:0]		SW,

	//////////// LED //////////
	output		     [3:0]		LED,
	output		     [3:0]		LED_BRACKET,

	//////////// SEG7 //////////
	output		          		HEX0_DP,
	output		     [6:0]		HEX0_D,
	output		          		HEX1_DP,
	output		     [6:0]		HEX1_D,

	//////////// FAN //////////
	input 		          		FAN_ALERT_n,
	output		          		FAN_I2C_SCL,
	inout 		          		FAN_I2C_SDA,

	//////////// FLASH //////////
	output		          		FLASH_ADV_n,
	output		    [26:1]		FLASH_A,
	output		     [1:0]		FLASH_CE_n,
	output		          		FLASH_CLK,
	inout 		    [31:0]		FLASH_D,
	inout 		          		FLASH_OE_n,
	input 		     [1:0]		FLASH_RDY_BSY_n,
	output		          		FLASH_RESET_n,
	output		          		FLASH_WE_n,

	//////////// TPS40428 //////////
	input 		          		TPS40428_ALERT,
	output		          		TPS40428_CLK,
	inout 		          		TPS40428_DATA,

	//////////// Temperature //////////
	output		          		TEMP_I2C_SCL,
	inout 		          		TEMP_I2C_SDA,
	input 		          		TEMP_INT_n,
	input 		          		TEMP_OVERT_n,

	//////////// POWER Monitor //////////
	input 		          		POWER_MONITOR_ALERT,
	output		          		POWER_MONITOR_I2C_SCL,
	inout 		          		POWER_MONITOR_I2C_SDA
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================



endmodule
